# -*- coding: utf-8 -*-
"""Different Set Operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ilPxt-_TQ2QBypUrziqvea1T-vIJjph-
"""

# Define two sets
set1 = {2, 4, 6, 8, 10}
set2 = {1, 2, 3, 4, 5}

# Union of set1 and set2
union_set = set1.union(set2)
print("Union of set1 and set2:", union_set)

# Intersection of set1 and set2
intersection_set = set1.intersection(set2)
print("Intersection of set1 and set2:", intersection_set)

# Difference between set1 and set2 (elements in set1 but not in set2)
difference_set1_set2 = set1.difference(set2)
print("Difference set1 - set2:", difference_set1_set2)

# Difference between set2 and set1 (elements in set2 but not in set1)
difference_set2_set1 = set2.difference(set1)
print("Difference set2 - set1:", difference_set2_set1)

# Symmetric difference (elements in either set1 or set2 but not in both)
symmetric_difference_set = set1.symmetric_difference(set2)
print("Symmetric difference of set1 and set2:", symmetric_difference_set)