# -*- coding: utf-8 -*-
"""fibonacci_nummber.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l7wJjrCpgwxCvXK-DntsjLmmfPm4R4ue
"""

def fib(n):
    a = 0
    b = 1
    if n <= 0:
        return
    elif n == 1:
        print(a)
    else:
        print(a)
        print(b)
        for i in range(2,n):
            c = a + b
            a = b
            b = c
            print(c)
# Ask the user how many Fibonacci numbers they want to see
num_terms = int(input("How many Fibonacci numbers do you want to generate? "))
fib(num_terms)