# -*- coding: utf-8 -*-
"""positive numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l7wJjrCpgwxCvXK-DntsjLmmfPm4R4ue
"""

def find_positive_numbers(list1, list2):
    # Initialize an empty list to store positive numbers
    positive_numbers = []

    # Iterate over each element in list1 and list2
    for num in list1 + list2:
        if num > 0:
            positive_numbers.append(num)

    return positive_numbers

# Example usage:
list1 = [12, -7, 5, 64, -14]
list2 = [12, 14, -95, 3]
positive_nums = find_positive_numbers(list1, list2)
print("Positive numbers from list1 and list2:", positive_nums)